### ISSUE TITLE
Cert problem for the website https://sic-software.com/

### ISSUE THREAD

**Issue by Neustradamus** [SICSoftwareGmbH/acts_as_removable#1]
Nothing directly but more important:
- Cert problem for the website https://sic-software.com/

Can you solve it?

**Comment by ydkn** [comment]
Thank you for pointing this out. I've fixed it.

**Comment by Neustradamus** [comment]
There is always a problem.

**Comment by themilkman** [comment]
> There is always a problem.

What is the problem? Cert seems valid here.

**Comment by Neustradamus** [comment]
Currently:
- https://www.sic-software.com/ works
- http://www.sic-software.com/ is redirected to https://www.sic-software.com/
- http://sic-software.com/ does not work
- https://sic-software.com/ does not work

http://www.sic-software.com/ + https://www.sic-software.com/ + http://sic-software.com/ must be redirected to https://sic-software.com/

All informations:
- https://dropwww.com/why

**Comment by themilkman** [comment]
For me all four link variants work fine and redirect to httpS?!

The www will be kept for other reasons.
